# Generated by Django 5.0.7 on 2024-07-13 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='Date created')),
                ('acquisition_date', models.CharField(max_length=200, verbose_name='Date acquired')),
                ('notes', models.TextField()),
                ('rarity', models.CharField(choices=[('COM', 'Common'), ('UNC', 'Uncommon'), ('RAR', 'Rare'), ('VRA', 'Very rare'), ('LEG', 'Legendary')], max_length=200)),
                ('price', models.JSONField()),
                ('party_owned', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
