# Generated by Django 5.0.7 on 2024-07-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('armor_type', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('shield', 'Shield')], max_length=50)),
                ('armor_class', models.CharField(max_length=50)),
                ('strength_requirement', models.IntegerField(blank=True, null=True)),
                ('stealth_disadvantage', models.BooleanField(default=False)),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('effect', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('charges', models.IntegerField(blank=True, default=0, help_text='Remaining charges', null=True)),
                ('max_charges', models.IntegerField(blank=True, default=0, help_text='Maximum charges', null=True)),
                ('recharge_type', models.CharField(choices=[('dawn', 'dawn'), ('long_r', 'long rest'), ('short_r', 'short rest'), ('dusk', 'dusk'), ('other', 'other')], max_length=200)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.baseitem', models.Model),
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('spell_name', models.CharField(max_length=200)),
                ('spell_level', models.IntegerField()),
                ('spell_effects', models.TextField()),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('charges', models.IntegerField(blank=True, default=0, help_text='Remaining charges', null=True)),
                ('max_charges', models.IntegerField(blank=True, default=0, help_text='Maximum charges', null=True)),
                ('recharge_type', models.CharField(choices=[('dawn', 'dawn'), ('long_r', 'long rest'), ('short_r', 'short rest'), ('dusk', 'dusk'), ('other', 'other')], max_length=200)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.baseitem', models.Model),
        ),
        migrations.CreateModel(
            name='Wand',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('charges', models.IntegerField(blank=True, default=0, help_text='Remaining charges', null=True)),
                ('max_charges', models.IntegerField(blank=True, default=0, help_text='Maximum charges', null=True)),
                ('recharge_type', models.CharField(choices=[('dawn', 'dawn'), ('long_r', 'long rest'), ('short_r', 'short rest'), ('dusk', 'dusk'), ('other', 'other')], max_length=200)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.baseitem', models.Model),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('weapon_type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=50)),
                ('damage', models.CharField(max_length=50)),
                ('properties', models.TextField()),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='WondrousItem',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('charges', models.IntegerField(blank=True, default=0, help_text='Remaining charges', null=True)),
                ('max_charges', models.IntegerField(blank=True, default=0, help_text='Maximum charges', null=True)),
                ('recharge_type', models.CharField(choices=[('dawn', 'dawn'), ('long_r', 'long rest'), ('short_r', 'short rest'), ('dusk', 'dusk'), ('other', 'other')], max_length=200)),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.baseitem', models.Model),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='attunement_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='baseitem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('very_rare', 'Very Rare'), ('legendary', 'Legendary')], default='common', max_length=200),
        ),
    ]
