# Generated by Django 5.0.7 on 2024-08-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseitem',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='baseitem',
            old_name='party_owned',
            new_name='is_party_owned',
        ),
    ]
